// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq4yzAtDGulC5BngYO7KdgOYOQKVPI5IQ',
    appId: '1:857770348887:web:abb5051104777454152e12',
    messagingSenderId: '857770348887',
    projectId: 'mbokaai-37a3b',
    authDomain: 'mbokaai-37a3b.firebaseapp.com',
    storageBucket: 'mbokaai-37a3b.firebasestorage.app',
    measurementId: 'G-434V1H09ZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAISym4G50-7935KFnI4kVMzKq1ephha8',
    appId: '1:857770348887:android:2bfe83a06dff7e2f152e12',
    messagingSenderId: '857770348887',
    projectId: 'mbokaai-37a3b',
    storageBucket: 'mbokaai-37a3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmKRdxkmewcBplyaEybojfisgvq4nzMlc',
    appId: '1:857770348887:ios:3563076fbd452ba5152e12',
    messagingSenderId: '857770348887',
    projectId: 'mbokaai-37a3b',
    storageBucket: 'mbokaai-37a3b.firebasestorage.app',
    iosBundleId: 'com.example.mbokaAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmKRdxkmewcBplyaEybojfisgvq4nzMlc',
    appId: '1:857770348887:ios:3563076fbd452ba5152e12',
    messagingSenderId: '857770348887',
    projectId: 'mbokaai-37a3b',
    storageBucket: 'mbokaai-37a3b.firebasestorage.app',
    iosBundleId: 'com.example.mbokaAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq4yzAtDGulC5BngYO7KdgOYOQKVPI5IQ',
    appId: '1:857770348887:web:0d9a672804b94fd0152e12',
    messagingSenderId: '857770348887',
    projectId: 'mbokaai-37a3b',
    authDomain: 'mbokaai-37a3b.firebaseapp.com',
    storageBucket: 'mbokaai-37a3b.firebasestorage.app',
    measurementId: 'G-C7QM7WW3YZ',
  );

}