// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5RoMq4uxbtAvXkdmt8ESfwZSthF58q0M',
    appId: '1:252157000221:web:c19810412e621537e324f4',
    messagingSenderId: '252157000221',
    projectId: 'mbokaai-67f82',
    authDomain: 'mbokaai-67f82.firebaseapp.com',
    storageBucket: 'mbokaai-67f82.firebasestorage.app',
    measurementId: 'G-Y1GDTPXSNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkG_wJf3MGTobaDT2d2uaZink28fGDLSg',
    appId: '1:252157000221:android:5e1b7f5bb1ca9ef2e324f4',
    messagingSenderId: '252157000221',
    projectId: 'mbokaai-67f82',
    storageBucket: 'mbokaai-67f82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA51x5wB_GVNZ123itWlp_b3HJANfCTW5U',
    appId: '1:252157000221:ios:c2d282205b44fdebe324f4',
    messagingSenderId: '252157000221',
    projectId: 'mbokaai-67f82',
    storageBucket: 'mbokaai-67f82.firebasestorage.app',
    iosBundleId: 'com.example.mbokaAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA51x5wB_GVNZ123itWlp_b3HJANfCTW5U',
    appId: '1:252157000221:ios:c2d282205b44fdebe324f4',
    messagingSenderId: '252157000221',
    projectId: 'mbokaai-67f82',
    storageBucket: 'mbokaai-67f82.firebasestorage.app',
    iosBundleId: 'com.example.mbokaAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5RoMq4uxbtAvXkdmt8ESfwZSthF58q0M',
    appId: '1:252157000221:web:40bab56709fe9933e324f4',
    messagingSenderId: '252157000221',
    projectId: 'mbokaai-67f82',
    authDomain: 'mbokaai-67f82.firebaseapp.com',
    storageBucket: 'mbokaai-67f82.firebasestorage.app',
    measurementId: 'G-DD0GZ2W6XQ',
  );

}